Bn 1031 library enhance contracthandler
bifrost-platform/bifrost-python-lib pull request #10
Opened 2023-02-16 07:28 UTC by dongchangYoo

Update methods of EthContractHandler
- get_contracts_by_event_name(event_name) returns all contracts related to the specific event
- get_contracts_name_by_event_name(event_name) returns all contract names related to the specific event

collect_event_in_limited_range(event_name, range_from, range_to)
- collect the specific event (emitted by related all contracts)
- implemented by a single eth_getLogs request

collect_every_event_in_limited_range(range_from, range_to)
- collect every event specified in config (emitted by related all contracts)
- implemented by using a single eth_getLogs request

collect_every_event(range_from, range_to)
- collect every event specified in config (emitted by related all contracts)
- implemented by using multi requests of the eth_getLogs
- the number of requests depends on EthContractHandler.max_log_num

collect_unchecked_single_chain_events(matured_only: bool)
- Essentially the same function as collect_every_event
- it calls collect_every_event method with self.last_height and current_height as input parameters

2023-02-16 07:32 UTC, dongchangYoo commented
여러 contract가 여러 종류의 event를 출력하더라도 get_logs 함수로 event를 모두 수집하도록 변경 했습니다.
이전에는 event가 추가 될때마다 get_logs 호출이 선형으로 늘었지만, 이제 부담 없이 event 종류를 추가할 수 있습니다.
이 버전으로 업데이트 하시면 (rpc request가 현저히 줄어서) observer recoder?의 성능이 높아질 것으로 기대합니다.
@yjkellyjoo

2023-02-16 07:33 UTC, dongchangYoo commented
tests/test_contracthandler.py에 테스트 코드 있으니 참고해주세요 @yjkellyjoo

2023-02-16 08:33 UTC, yjkellyjoo commented on chainpy/eth/managers/contracthandler.py
> +                event_name, contract_name = event["event_name"], event["contract_name"]
contract_name l.71에서 정의 했는데 또 하네요
```suggestion
                event_name, contract_name = event["event_name"], event["contract_name"]
                if self._contracts.get(contract_name) is None:
                    raise Exception("Event of unknown contract: {}".format(event))
```

2023-02-16 08:33 UTC, yjkellyjoo commented on chainpy/eth/managers/contracthandler.py
> +        return [data["contract"] for data in self._event_db[event_name]]
l.138에서 이미 `data`로 `self._event_db[event_name]`를 꺼냈으니 또 꺼낼 필요 없을 것 같습니다
```suggestion
        return [event["contract"] for event in data]
```

2023-02-16 08:34 UTC, yjkellyjoo commented
제가 BN-1031 브랜치로 받아서 돌려보고 문제 없으면 approve 찍으러 다시 올게요!

2023-02-17 05:27 UTC, yjkellyjoo requested changes

2023-02-17 05:27 UTC, yjkellyjoo commented on chainpy/eth/managers/contracthandler.py
> -        self.latest_height = to_block + 1
원래 small_ranged_collect_events()에 있던 self.latest_height값을 update하는 부분이 현재 수정된 코드에서는 collect_unchecked_single_chain_events()에서 하는 것으로 보입니다 (l.259).
제가 chainpy를 사용하는 부분에서 self.latest_height값이 꼭 small_ranged_collect_events()에서 업데이트가 되어야만 했어서 이전에 이렇게 개선을 했던거라, 이번에 업데이트 된 코드에서도 가장 안쪽(?) 단위인 collect_every_event_in_limited_range()에서 self.latest_height값을 업데이트 하는 방향으로 수정이 되었으면 좋겠습니다! 
그리고 collect_event_in_limited_range()를 현재 사용하는 곳은 없지만 legacy 때문에 기능을 남겨둔 것으로 이해했는데, 위 처럼 바뀐다면 여기에도 self.latest_height를 업데이트 하는 코드가 들어가야할 것 같습니다.

2023-02-17 08:39 UTC, dongchangYoo commented on chainpy/eth/managers/contracthandler.py
> -        self.latest_height = to_block + 1
latest_height의 setter를 만들어 두었습니다.
밖에서 collect_every_event 함수를 쓰시면 되구요. 밖에서 이 값을 업데이트 하시면 됩니다

2023-02-17 08:41 UTC, dongchangYoo commented on chainpy/eth/managers/contracthandler.py
> -        self.latest_height = to_block + 1
collect_every_event (이전에 small_... 이었던) 안에서 self.latest_height를 업데이트 하면, 업데이트를 안하고자 하는 프로그램을 만들 수가 없습니다.
그래서 range를 입력해야하는 collect_every_event의 경우 latest_height를 업데이트 안하는 방향으로 구현했고,
range를 안받는 collect_unchecked_single_chain_events 함수는 latest_height를 업데이트 하는 방향으로 구현했습니다

2023-02-17 09:25 UTC, merged